server:
  port: 8080

spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/sosialhjelp-soknad-db
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/sosialhjelp-soknad-db
    username: postgres
    password: postgres
logging:
  level:
    root: debug


management:
  endpoints:
    web:
      base-path: "/internal"
      exposure:
        include: metrics, prometheus

soknad_api_migration_api_url: http://localhost:3000/sosialhjelp/soknad-api/internal/migration
