spring:
  main:
    banner-mode: off
  flyway:
    enabled: true

# Prometheus
management:
  endpoints:
    web:
      base-path: "/internal"
      exposure:
        include: info, health, metrics, prometheus
