apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-soknad-api-db-migration
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 256Mi
  ingresses:
    - "https://sosialhjelp-soknad-api-db-migration.intern.nav.no"
  azure:
    application:
      enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "log-kibana"
    - name: SOKNAD_API_MIGRATION_API_URL
      value: "http://sosialhjelp-soknad-api/sosialhjelp/soknad-api/internal/migration"