name: 'Remove old images'
on:
  schedule: ## Kjører kl. 05:00 mandag (schedule kjører bare for Default branch)
    - cron: '*/5 * * * *'

jobs:
  remove-images:
    name: 'Remove old images job except 50 most recent'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'sosialhjelp-soknad-api-db-migration/sosialhjelp-soknad-api-db-migration'
          package-type: 'container'
          min-versions-to-keep: 50
